<a href="https://colab.research.google.com/github/Penn2001/MSSP-607/blob/main/WeeklyModules/Week06/Participation_Activity_Week6_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Lambda Functions:

This is used for MSSP 607

This notebook is an example of how lamda functions works.  For more information see https://docs.python.org/3/reference/expressions.html#lambda'

As we dicussed in class, Lambda Functions which are anonymous functions meaning they are not bound by names. The unamed object behaves like a function object.   

The format of a Lambda function is: **lambda ::= [parameter lists] ":" expression**.  Note that functions created with lambda expressions cannot contain statements or annotations; lambda functions contain a single valid python expression.  Also, the Lambda function can only have one expression.

**Definition: Expression:** A piece of syntax which can be evaluated to some value. In other words, an expression is an accumulation of expression elements like literals, names, attribute access, operators or function calls which all return a value. In contrast to many other languages, not all language constructs are expressions. There are also statements which cannot be used as expressions, such as while. Assignments are also statements, not expressions.

See: https://docs.python.org/3/glossary.html#term-expression

Lamda functions are shorthand representations of functions that allow us to write concise code without multiple lines.

In [25]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [26]:
%run '/content/drive/MyDrive/Google_connection.py'

Changed directoGit_HUBry to: /content/MSSP-607/data/MSSP-607

In [27]:
%pushd "/content/MSSP-607/data"

/content/MSSP-607/data

['/content/MSSP-607/data/MSSP-607',
 '/content/MSSP-607/data/MSSP-607',
 '/content/MSSP-607',
 '/content']

In [28]:
import pandas as pd

In [29]:
df=pd.read_csv('Student Performance Data.csv') #Input the Student Performance data set into a Pandas Data Frame.
df

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,88,99,95,282,completed,high
996,male,group C,high school,free/reduced,62,55,55,172,none,medium
997,female,group C,high school,free/reduced,59,71,65,195,completed,medium
998,female,group D,some college,standard,68,78,77,223,completed,high
999,female,group D,some college,free/reduced,77,86,86,249,none,high

In [30]:
#The lambda declaration creates an non-named object that acts as a function in that it is given values, evaluates those
# values, and returns a result.

x = lambda a,b : a +b+ 10   #defines and object with one or more parameters, with one expression that returns a result.

print(x(15,10))

35

In [31]:
#We can also return lambda functions as a result
def find_number (x): #Define a function
    return lambda x: x+(2**3) #return lambda function and assign it to a variable

new_number_one = find_number(0) #new_number_one calls find_number function and is assigned the lambda function lambda x: x+(2**3)
new_number_two = find_number(0) #new_number_two calls find_number function and is assigned the lambda function lambda x: x+(2**3)
print(new_number_one(3), new_number_two(2)) #Send the newly defined function parameters and evaluate the results. 3+(2**3) = 11, 2+(2**3) = 10.

11 10

In [32]:
#Lamda functions can be used inside statements to evaluate and expression requring results.
df["reading score"] = df["reading score"].apply(lambda x: x-2) #Changes the reading score by subtracting 2 from the current values in the series.

print(df["reading score"])

0      70
1      88
2      93
3      55
4      76
       ..
995    97
996    53
997    69
998    76
999    84
Name: reading score, Length: 1000, dtype: int64

In [33]:
df #Notice that the total score series is unchanged so our dataframe is inaccurate.  Total Score should be 216, 245, etc.

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,70,74,218,none,medium
1,female,group C,some college,standard,69,88,88,247,completed,high
2,female,group B,master's degree,standard,90,93,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,55,44,148,none,low
4,male,group C,some college,standard,76,76,75,229,none,high
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,88,97,95,282,completed,high
996,male,group C,high school,free/reduced,62,53,55,172,none,medium
997,female,group C,high school,free/reduced,59,69,65,195,completed,medium
998,female,group D,some college,standard,68,76,77,223,completed,high
999,female,group D,some college,free/reduced,77,84,86,249,none,high

In [34]:
df["total score"] = df["math score"]+df["reading score"]+df["writing score"]
df

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,70,74,216,none,medium
1,female,group C,some college,standard,69,88,88,245,completed,high
2,female,group B,master's degree,standard,90,93,93,276,none,high
3,male,group A,associate's degree,free/reduced,47,55,44,146,none,low
4,male,group C,some college,standard,76,76,75,227,none,high
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,88,97,95,280,completed,high
996,male,group C,high school,free/reduced,62,53,55,170,none,medium
997,female,group C,high school,free/reduced,59,69,65,193,completed,medium
998,female,group D,some college,standard,68,76,77,221,completed,high
999,female,group D,some college,free/reduced,77,84,86,247,none,high

In [35]:
#We can add series as well using the lambda function
df_newdf = df.assign(Percentage = lambda x: (x['total score'] /300 * 100))  # Adds a Percentage Series to the dataframe assuming the total for each test is 100
df_newdf #createing a new data frame.

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect,Percentage
0,female,group B,bachelor's degree,standard,72,70,74,216,none,medium,72.00
1,female,group C,some college,standard,69,88,88,245,completed,high,81.67
2,female,group B,master's degree,standard,90,93,93,276,none,high,92.00
3,male,group A,associate's degree,free/reduced,47,55,44,146,none,low,48.67
4,male,group C,some college,standard,76,76,75,227,none,high,75.67
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,88,97,95,280,completed,high,93.33
996,male,group C,high school,free/reduced,62,53,55,170,none,medium,56.67
997,female,group C,high school,free/reduced,59,69,65,193,completed,medium,64.33
998,female,group D,some college,standard,68,76,77,221,completed,high,73.67
999,female,group D,some college,free/reduced,77,84,86,247,none,high,82.33

In [36]:
df_newdf = df.assign(language_score = lambda x: (((x['reading score']+x['writing score']))/200)*100)
df_newdf

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect,language_score
0,female,group B,bachelor's degree,standard,72,70,74,216,none,medium,72.00
1,female,group C,some college,standard,69,88,88,245,completed,high,88.00
2,female,group B,master's degree,standard,90,93,93,276,none,high,93.00
3,male,group A,associate's degree,free/reduced,47,55,44,146,none,low,49.50
4,male,group C,some college,standard,76,76,75,227,none,high,75.50
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,88,97,95,280,completed,high,96.00
996,male,group C,high school,free/reduced,62,53,55,170,none,medium,54.00
997,female,group C,high school,free/reduced,59,69,65,193,completed,medium,67.00
998,female,group D,some college,standard,68,76,77,221,completed,high,76.50
999,female,group D,some college,free/reduced,77,84,86,247,none,high,85.00